# Generated by Django 4.2.11 on 2024-12-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formfield",
            options={"ordering": ["priority"]},
        ),
        migrations.AddField(
            model_name="formfield",
            name="priority",
            field=models.PositiveIntegerField(
                default=0, help_text="Priority for ordering the fields."
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("image", "Image"),
                    ("textarea", "TextArea"),
                    ("choice", "Choice"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("radio", "Radio"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="options",
            field=models.JSONField(
                blank=True,
                help_text="Options for choice/select fields. Example: [{'value': 'Option 1'}, {'value': 'Option 2'}]",
                null=True,
            ),
        ),
    ]
