# Generated by Django 5.1.4 on 2025-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_formfield_options_formfield_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("image", "Image"),
                    ("textarea", "TextArea"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("radio", "Radio"),
                ],
                max_length=10,
            ),
        ),
    ]
