# Generated by Django 5.1.4 on 2025-01-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_formfield_file_alter_formfield_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("image", "Image"),
                    ("file", "File"),
                    ("textarea", "TextArea"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("radio", "Radio"),
                ],
                max_length=10,
            ),
        ),
    ]
