# Generated by Django 5.1.4 on 2025-01-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_formfield_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("demand_submission", "Demand Submission"),
                    ("agent_registration", "Agent Registration"),
                    ("worker_registration", "Worker Registration"),
                    ("apply_now", "Apply Now"),
                ],
                max_length=50,
            ),
        ),
    ]
