# Generated by Django 5.1.4 on 2025-01-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_form_form_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100)),
                ("requirements", models.TextField()),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="job_posters/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="formfield",
            name="is_job_field",
            field=models.BooleanField(default=False),
        ),
    ]
