# Generated by Django 5.1.4 on 2025-01-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_job_formfield_is_job_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="uploaded_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
