# Generated by Django 5.1.4 on 2025-03-09 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_bkashtoken_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="form_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="api.formresponse",
            ),
        ),
    ]
