# Generated by Django 4.2.10 on 2025-03-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_payment_form_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
