# Generated by Django 4.2.10 on 2025-03-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_form_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
